<style>
    .example-popup {
        position: relative;
        background: #FFF;
        padding: 20px;
        width: auto;
        max-width: 500px;
        margin: 20px auto;
    }
</style>
<div id="ajax-content" class="example-popup">
    <p>Content</p>
</div>

<script>
    debugger;
        let cookieContent = document.getElementsById('cookie-status');
        cookieContent.innerHTML = '';
        cookieContent.innerHTML = '<button title="Close (Esc)" type="button" class="mfp-close">×</button>';
</script>
