<!-- Footer
		============================================= -->
		<footer id="footer" class="dark">
			<div class="container">

				<!-- Footer Widgets
				============================================= -->
				<div class="footer-widgets-wrap">
					<div class="row">
						<div class="col-md-12">
							<div class="widget clearfix text-center">
								<img src="images/ducati-footer.svg" alt="Image" class="text-center pb-5" width="500">
							</div>
							<div class="row">
								<div class="col-lg-6 offset-lg-3">
									<div class="row center">
										<div class="col-4">
											<p class="gris-ducati">
												TÉRMINOS DE USO
											</p>
										</div>
										<div class="col-4">
											<p class="gris-ducati">
												AVISO DE PRIVACIDAD
											</p>
										</div>
										<div class="col-4">
											<p class="gris-ducati">
												INFORMACIÓN DE COOKIES
											</p>
										</div>
									</div>
									<p class="text-center" style="color: #666;">Copyright © 2023 Ducati Motor Holding S.p.A – A Sole Shareholder Company - A Company subject to the Management and Coordination activities of AUDI AG. All rights reserved. VAT 05113870967</p>
								</div>
							</div>
						</div>
						<div class="col-md-12 text-center">
							<div class="d-flex justify-content-center">
								<a href="#" class="social-icon si-small si-borderless si-facebook">
									<i class="icon-facebook"></i>
									<i class="icon-facebook"></i>
								</a>

								<a href="#" class="social-icon si-small si-borderless si-instagram">
									<i class="icon-instagram"></i>
									<i class="icon-instagram"></i>
								</a>
							</div>
							<div class="clear"></div>
						</div>
					</div>
				</div><!-- .footer-widgets-wrap end -->

			</div>

		</footer><!-- #footer end -->