<style>
    @media (min-width: 992px) {

        #top-bar.transparent-topbar {
            z-index: 399;
            border-bottom: 0;
            margin-top: 15px;
        }

        #top-bar.transparent-topbar {
            background: transparent !important;
        }

        #top-bar + #header.transparent-header.floating-header {
            margin-top: 15px;
        }

    }

    .dark .top-links li > a,
    .dark #top-social li a { color: #FFF; }

    .dark .top-links li:hover { background-color: rgba(255,255,255,0.15); }

    .dark #top-social li { border-left: 0; }
</style>
<!-- Header
		============================================= -->
		
			<div id="header-wrap">
				<div class="container">
					<div class="header-row justify-content-between mobil-menu">

						<!-- Logo
						============================================= -->
						<div id="logo" class="order-lg-2 col-auto p-3 me-lg-0">
							<a href="index.html" class="standard-logo" data-dark-logo="images/ducati_logo.png"><img src="images/ducati_logo.png" alt="Ducati Logo" style="width: 50%; height: 50%;"></a>
							<a href="index.html" class="retina-logo" data-dark-logo="images/ducati_logo.png"><img src="images/ducati_logo.png" alt="Ducati Logo" style="width: 30%; height: 30%;"></a>
						</div><!-- #logo end -->

						<div id="primary-menu-trigger">
							<svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
						</div>

						<!-- Primary Navigation
						============================================= -->
						<nav class="primary-menu order-lg-1 col-lg-5 px-0 on-click" style="position:inherit;">

							<ul class="one-page-menu menu-container" data-easing="easeInOutExpo" data-speed="1250" data-offset="65">
								<li class="menu-item mega-menu mega-menu-full">
									<a class="menu-link" href="#"><div>Modelos</div></a>
									<div class="mega-menu-content mega-menu-style-2">
										<div class="container">
											<div class="row">
												<ul class="sub-menu-container mega-menu-column col-12">
													<li class="menu-item">
														<div class="widget">

															<!-- Portfolio Items
															============================================= -->
															<div id="portfolio" class="portfolio row gutter-20">

																<article class="portfolio-item col-lg-1-5 col-md-4 col-sm-6 col-12 pf-media pf-icons">
																	<div class="grid-inner">
																		<div class="portfolio-image">
																			<a href="#">
																				<img src="images/modelos/MY23-Diavel-V4-Rd-NEW-Model-Blocks-630x390.png" alt="Diavel V4">
																			</a>
																		</div>
																		<div class="portfolio-desc text-center">
																			<h4 class="gris-ducati"><a class="gris-ducati" href="#">Diavel 4</a></h4>
																		</div>
																	</div>
																</article>

																<article class="portfolio-item col-lg-1-5 col-md-4 col-sm-6 col-12 pf-media pf-icons">
																	<div class="grid-inner">
																		<div class="portfolio-image">
																			<a href="#">
																				<img src="images/modelos/MY23-Panigale-V4R-NEW-Model-Blocks-630x390.png" alt="Diavel V4">
																			</a>
																		</div>
																		<div class="portfolio-desc text-center">
																			<h4 class="gris-ducati"><a class="gris-ducati" href="#">Panigale V4 R</a></h4>
																		</div>
																	</div>
																</article>

																<article class="portfolio-item col-lg-1-5 col-md-4 col-sm-6 col-12 pf-media pf-icons">
																	<div class="grid-inner">
																		<div class="portfolio-image">
																			<a href="#">
																				<img src="images/modelos/MY23-Multistrada-V4-Rally-Radar-Gr-NEW-Model-Blocks-630x390.png" alt="Diavel V4">
																			</a>
																		</div>
																		<div class="portfolio-desc text-center">
																			<h4 class="gris-ducati"><a class="gris-ducati" href="#">Multistrada V4 Rally</a></h4>
																		</div>
																	</div>
																</article>

																<article class="portfolio-item col-lg-1-5 col-md-4 col-sm-6 col-12 pf-media pf-icons">
																	<div class="grid-inner">
																		<div class="portfolio-image">
																			<a href="#">
																				<img src="images/modelos/MY23-Streetfighter-V4-SP2-NEW-Model-Blocks-630x390.png" alt="Diavel V4">
																			</a>
																		</div>
																		<div class="portfolio-desc text-center">
																			<h4 class="gris-ducati"><a class="gris-ducati" href="#">Streetfighter V4 SP2</a></h4>
																		</div>
																	</div>
																</article>

															</div>

														</div>
													</li>
												</ul>
											</div>
										</div>
									</div>
								</li>
								<li class="menu-item">
									<a class="menu-link" href="#"><div>Equipamiento</div></a>
									<ul class="sub-menu-container">
										<li class="menu-item">
											<a class="menu-link" href="accesorios.html"><div>Accesorios</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="ropa.html"><div>Ropa</div></a>
										</li>
									</ul>
								</li>
								<li class="menu-item">
									<a href="blog.html" class="menu-link"><div>Ducati world</div></a>
								</li>
							</ul>

						</nav>

						<nav class="primary-menu order-lg-3 col-lg-5 px-0" style="position:inherit;">

							<ul class="one-page-menu menu-container justify-content-lg-end" data-easing="easeInOutExpo" data-speed="1250" data-offset="65">
								<li class="menu-item">
									<a href="#" class="menu-link" data-href="#section-services"><div><img src="images/icono-map.png" class="img-fluid" width="20"></div></a>
								</li>
								<li class="menu-item">
									<a href="#" class="menu-link" data-href="#section-blog"><div><img src="images/icono-tel.png" class="img-fluid" width="15"></div></a>
								</li>
								<li class="menu-item">
									<a href="#" class="menu-link" data-href="#section-contact"><div><img src="images/icono-whatsapp.png" class="img-fluid" width="20"></div></a>
								</li>
							</ul>

						</nav><!-- #primary-menu end -->

					</div>
				</div>
			</div>
			<div class="header-wrap-clone"></div>
        <script>
            require(['functions', 'plugins'], function(){

            });
        </script>